"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { formatDate, INSURANCE_CASE_TYPE_LABELS, INSURANCE_STATUS_LABELS, type InsuranceCaseType, type InsuranceStatus } from "@/lib/insurance-arbitration/presentation";
import styles from "./page.module.css";

type RecordItem = { id: string; referenceNumber: string; arbitrationApplicationNo: string | null; vehiclePlate: string; vehicleOwner: string; opposingInsuranceCompany: string; opposingPolicyNumber: string | null; accidentDate: string; insuranceApplicationDate: string | null; arbitrationApplicationDate: string | null; caseTypes: InsuranceCaseType[]; status: InsuranceStatus; updatedAt: string };
type Result = { items: RecordItem[]; pagination: { page: number; pageSize: number; pageCount: number; totalCount: number }; summary: { total: number; arbitration: number; insurance: number; followUp: number; completed: number } };
type Tab = "ALL" | "ARBITRATION" | "INSURANCE" | "FOLLOW_UP" | "COMPLETED";
const emptyResult: Result = { items: [], pagination: { page: 1, pageSize: 10, pageCount: 1, totalCount: 0 }, summary: { total: 0, arbitration: 0, insurance: 0, followUp: 0, completed: 0 } };

function Icon({ name }: { name: "folder" | "gavel" | "shield" | "check" | "search" | "plus" | "eye" | "edit" }) {
  const paths = { folder: <path d="M3 6h7l2 3h9v10H3Z" />, gavel: <><path d="m14 4 6 6M11 7l6 6M4 20l8-8" /><path d="m9 4 3-3 7 7-3 3Z" /></>, shield: <path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6Z" />, check: <><circle cx="12" cy="12" r="9" /><path d="m8 12 3 3 5-6" /></>, search: <><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></>, plus: <path d="M12 5v14M5 12h14" />, eye: <><path d="M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Z" /><circle cx="12" cy="12" r="2.5" /></>, edit: <path d="m4 20 4-1 11-11-3-3L5 16Z" /> };
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>;
}

export default function InsuranceArbitrationClient() {
  const [result, setResult] = useState<Result>(emptyResult); const [query, setQuery] = useState(""); const [debounced, setDebounced] = useState(""); const [tab, setTab] = useState<Tab>("ALL"); const [arbitration, setArbitration] = useState("ALL"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const timeout = window.setTimeout(() => setDebounced(query.trim()), 300); return () => window.clearTimeout(timeout); }, [query]);
  const status = tab === "ARBITRATION" ? "ARBITRATION_GROUP" : tab === "INSURANCE" ? "INSURANCE_GROUP" : tab === "FOLLOW_UP" ? "FOLLOW_UP_GROUP" : tab === "COMPLETED" ? "COMPLETED_GROUP" : "ALL";
  useEffect(() => { const controller = new AbortController(); async function load() { setLoading(true); setError(""); try { const parameters = new URLSearchParams({ query: debounced, status, arbitration, dateFrom, dateTo, page: String(page), pageSize: String(pageSize) }); const response = await fetch(`/api/insurance-arbitration?${parameters}`, { credentials: "same-origin", cache: "no-store", signal: controller.signal }); const body = await response.json(); if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Dosyalar yüklenemedi."); setResult(body.data as Result); } catch (cause) { if (cause instanceof DOMException && cause.name === "AbortError") return; setError(cause instanceof Error ? cause.message : "Dosyalar yüklenemedi."); } finally { if (!controller.signal.aborted) setLoading(false); } } void load(); return () => controller.abort(); }, [arbitration, dateFrom, dateTo, debounced, page, pageSize, status]);
  const cards = [{ key: "total", tab: "ALL", label: "Toplam Dosya", hint: "Tüm kayıtlar", value: result.summary.total, icon: "folder", tone: "blue" }, { key: "arbitration", tab: "ARBITRATION", label: "Tahkimde", hint: "Tahkim süreci", value: result.summary.arbitration, icon: "gavel", tone: "green" }, { key: "insurance", tab: "INSURANCE", label: "Sigorta", hint: "Sigorta süreci", value: result.summary.insurance, icon: "shield", tone: "yellow" }, { key: "followUp", tab: "FOLLOW_UP", label: "Takip / Dava", hint: "Ödeme, icra ve dava", value: result.summary.followUp, icon: "folder", tone: "purple" }, { key: "completed", tab: "COMPLETED", label: "Tamamlandı", hint: "Kapanan dosyalar", value: result.summary.completed, icon: "check", tone: "cyan" }] as const;
  function clear() { setQuery(""); setArbitration("ALL"); setDateFrom(""); setDateTo(""); setTab("ALL"); setPage(1); }
  return <main className={styles.page}>
    <section className={styles.cards}>{cards.map((card) => <button type="button" aria-pressed={tab === card.tab} className={`${styles[card.tone]} ${tab === card.tab ? styles.activeCard : ""}`} key={card.key} onClick={() => { setTab(card.tab); setArbitration("ALL"); setPage(1); }}><span><Icon name={card.icon} /></span><div><strong>{card.value}</strong><p>{card.label}</p><small>{card.hint}</small></div></button>)}</section>
    <section className={styles.workspace}><header className={styles.workspaceToolbar}><div className={styles.listTitle}><strong>Dosya Listesi</strong><span>{result.pagination.totalCount} kayıt</span></div><div className={styles.toolbarFilters}><label className={styles.dateFilter}><span>Tarih Aralığı</span><div><input aria-label="Başlangıç tarihi" type="date" value={dateFrom} onChange={(e) => { setDateFrom(e.target.value); setPage(1); }} /><input aria-label="Bitiş tarihi" type="date" value={dateTo} onChange={(e) => { setDateTo(e.target.value); setPage(1); }} /></div></label><label className={styles.search}><span>Dosya Ara</span><div><Icon name="search" /><input aria-label="Dosya ara" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="TC/VKN, müvekkil, plaka veya poliçe no..." /></div></label><label className={styles.arbitrationFilter}><span>Tahkim</span><select value={arbitration} onChange={(e) => { setArbitration(e.target.value); setPage(1); }}><option value="ALL">Tümü</option><option value="YES">Var</option><option value="NO">Yok</option></select></label><button type="button" className={styles.clear} onClick={clear}>Temizle</button><Link href="/sigorta-ve-tahkim/yeni"><Icon name="plus" />Yeni Dosya Ekle</Link></div></header>
      {error && <p className={styles.error}>{error}</p>}
      <section className={styles.list}>
        <div className={styles.tableWrap}><table>
          <thead><tr><th>#</th><th>Tahkim Başvuru No</th><th>Plaka</th><th>Müvekkil Adı</th><th>Karşı Sigorta</th><th>Karşı Poliçe</th><th>Kaza Tarihi</th><th>Sigorta Başvuru Tarihi</th><th>Tahkim Başvuru Tarihi</th><th>Dosya Türü</th><th>Dosya Durumu</th><th>Son İşlem Tarihi</th><th>İşlemler</th></tr></thead>
          <tbody>
            {!loading && result.items.map((item, index) => <tr key={item.id}><td>{(result.pagination.page - 1) * result.pagination.pageSize + index + 1}</td><td>{item.arbitrationApplicationNo ?? item.referenceNumber}</td><td>{item.vehiclePlate}</td><td>{item.vehicleOwner}</td><td>{item.opposingInsuranceCompany}</td><td>{item.opposingPolicyNumber ?? "—"}</td><td>{formatDate(item.accidentDate)}</td><td>{formatDate(item.insuranceApplicationDate)}</td><td>{formatDate(item.arbitrationApplicationDate)}</td><td>{item.caseTypes.map((type) => INSURANCE_CASE_TYPE_LABELS[type]).join(", ")}</td><td><span className={`${styles.status} ${styles[`status_${item.status}`]}`}>{INSURANCE_STATUS_LABELS[item.status]}</span></td><td>{formatDate(item.updatedAt.slice(0, 10))}</td><td><div className={styles.actions}><Link href={`/sigorta-ve-tahkim/${item.id}`} title="Görüntüle" aria-label="Dosyayı görüntüle"><Icon name="eye" /></Link><Link href={`/sigorta-ve-tahkim/${item.id}/duzenle`} title="Düzenle" aria-label="Dosyayı düzenle"><Icon name="edit" /></Link></div></td></tr>)}
            {loading && <tr><td colSpan={13} className={styles.empty}>Dosyalar yükleniyor…</td></tr>}
            {!loading && !result.items.length && <tr><td colSpan={13} className={styles.empty}>Henüz kayıtlı dosya bulunmuyor.</td></tr>}
          </tbody>
        </table></div>
        <footer><p>Toplam {result.pagination.totalCount} kayıt listeleniyor.</p><div><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>‹</button><b>{page}</b><button type="button" disabled={page === result.pagination.pageCount} onClick={() => setPage((value) => value + 1)}>›</button><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option value="10">10 / sayfa</option><option value="20">20 / sayfa</option><option value="50">50 / sayfa</option></select></div></footer></section>
    </section></main>;
}
