import { NextResponse } from "next/server";
import { ApiRequestError, assertSameOrigin, readJsonBody, requireApiSession } from "@/lib/api-security";
import { deleteGeneralCaseTask, GeneralCaseTaskLockedError, updateGeneralCaseTask } from "@/lib/general-legal-cases/activity-service";
import { GeneralLegalCaseNotFoundError } from "@/lib/general-legal-cases/read";
import { notificationInputSchema } from "@/lib/notification-input";
import { resourceIdSchema } from "@/lib/resource-id";
type Context = { params: Promise<{ id: string; notificationId: string }> };
export async function PATCH(request: Request, context: Context) { try { assertSameOrigin(request); const session = await requireApiSession(request); const ids = await readIds(context); const input = notificationInputSchema.safeParse(await readJsonBody(request)); if (!input.success) return json({ error: { message: "Bildirim bilgileri geçerli değil.", fields: input.error.flatten().fieldErrors } }, 400); return json({ data: await updateGeneralCaseTask(ids.id, ids.notificationId, input.data, { id: session.user.id, role: session.user.role }) }, 200); } catch (error) { return handle(error, "Bildirim güncellenemedi."); } }
export async function DELETE(request: Request, context: Context) { try { assertSameOrigin(request); const session = await requireApiSession(request); const ids = await readIds(context); await deleteGeneralCaseTask(ids.id, ids.notificationId, { id: session.user.id, role: session.user.role }); return json({ data: { deleted: true } }, 200); } catch (error) { return handle(error, "Bildirim silinemedi."); } }
async function readIds(context: Context) { const values = await context.params; const id = resourceIdSchema.safeParse(values.id); const notificationId = resourceIdSchema.safeParse(values.notificationId); if (!id.success || !notificationId.success) throw new ApiRequestError(404, "NOT_FOUND", "Bildirim bulunamadı."); return { id: id.data, notificationId: notificationId.data }; }
function handle(error: unknown, message: string) { if (error instanceof ApiRequestError) return json({ error: { message: error.message } }, error.status); if (error instanceof GeneralCaseTaskLockedError) return json({ error: { message: "Gönderime alınmış bildirim düzenlenemez." } }, 409); if (error instanceof GeneralLegalCaseNotFoundError) return json({ error: { message: "Bildirim bulunamadı." } }, 404); console.error(message, error); return json({ error: { message } }, 500); }
function json(body: unknown, status: number) { return NextResponse.json(body, { status, headers: { "Cache-Control": "no-store" } }); }
