import { Prisma } from "@/generated/prisma/client";
import { ApiRequestError, assertSameOrigin, readJsonBody, requireApiSession } from "@/lib/api-security";
import { insuranceCaseInputSchema } from "@/lib/insurance-arbitration/input";
import { createInsuranceCase, listInsuranceCases } from "@/lib/insurance-arbitration/service";
import { NextResponse } from "next/server";
import { z } from "zod";

const statuses = ["ALL", "ARBITRATION_GROUP", "INSURANCE_GROUP", "FOLLOW_UP_GROUP", "COMPLETED_GROUP", "INSURANCE_APPLICATION", "SETTLEMENT_REVIEW", "ARBITRATION_APPLICATION", "ARBITRATION", "EXPERT_REVIEW", "PAYMENT_PENDING", "INSURANCE_PAYMENT_RECEIVED", "ENFORCEMENT", "LITIGATION", "COMPLETED", "CLOSED"] as const;
const querySchema = z.object({ query: z.string().trim().max(200).default(""), status: z.enum(statuses).default("ALL"), arbitration: z.enum(["ALL", "YES", "NO"]).default("ALL"), dateFrom: z.union([z.string().regex(/^\d{4}-\d{2}-\d{2}$/), z.literal("")]).default("").transform((value) => value || null), dateTo: z.union([z.string().regex(/^\d{4}-\d{2}-\d{2}$/), z.literal("")]).default("").transform((value) => value || null), page: z.coerce.number().int().min(1).max(1_000_000).default(1), pageSize: z.coerce.number().int().refine((value) => [10, 20, 50].includes(value)).default(10) }).strict();

export async function GET(request: Request) { try { await requireApiSession(request); const validation = querySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams.entries())); if (!validation.success) return response({ error: { message: "Filtre bilgileri geçerli değil." } }, 400); return response({ data: await listInsuranceCases(validation.data) }, 200); } catch (error) { return handle(error, "Sigorta ve tahkim dosyaları yüklenemedi."); } }
export async function POST(request: Request) { try { assertSameOrigin(request); const session = await requireApiSession(request); const validation = insuranceCaseInputSchema.safeParse(await readJsonBody(request)); if (!validation.success) return response({ error: { message: "Dosya bilgileri geçerli değil.", fields: validation.error.flatten().fieldErrors } }, 400); return response({ data: await createInsuranceCase(validation.data, session.user.id) }, 201); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return response({ error: { message: "Bu tahkim başvuru numarası zaten kayıtlı." } }, 409); return handle(error, "Sigorta ve tahkim dosyası oluşturulamadı."); } }
function handle(error: unknown, message: string) { if (error instanceof ApiRequestError) return response({ error: { message: error.message } }, error.status); console.error(message, { error: error instanceof Error ? error.name : "UnknownError" }); return response({ error: { message } }, 500); }
function response(body: unknown, status: number) { return NextResponse.json(body, { status, headers: { "Cache-Control": "no-store" } }); }
