"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import AppShell from "@/components/app-shell/AppShell";
import { formatMoneyInput, limitDateYear } from "@/lib/form-input";
import { INSURANCE_CASE_TYPE_LABELS, INSURANCE_STATUS_LABELS, type InsuranceCaseType } from "@/lib/insurance-arbitration/presentation";
import PaymentSection, { type InsurancePaymentEntry } from "./PaymentSection";
import styles from "./page.module.css";

type Errors = Record<string, string[] | undefined>;
type MoneyField = "insuranceSettlementOffer" | "postageExpense" | "enforcementExpense" | "arbitrationApplicationFee" | "expertFee" | "postalAmount" | "actualDepreciationAmount";
type Tab = "general" | "payments" | "description" | "documents";
const initialForm = { arbitrationApplicationNo: "", opposingInsuranceCompany: "", opposingPolicyNumber: "", policyExpiryDate: "", opposingVehicleOwner: "", opposingIdentityNumber: "", vehicleOwner: "", identityNumber: "", vehiclePlate: "", accidentDate: "", postalDeliveryDate: "", caseTypes: ["DEPRECIATION"] as InsuranceCaseType[], insuranceApplicationDate: "", insuranceSettlementOffer: "0", arbitrationApplicationDate: "", hasArbitration: false, arbitrationCaseNumber: "", status: "INSURANCE_APPLICATION", postageExpense: "0", enforcementExpense: "0", arbitrationApplicationFee: "0", expertFee: "0", postalAmount: "0", actualDepreciationAmount: "0", description: "" };

export default function NewInsuranceCaseForm() {
  const router = useRouter();
  const [form, setForm] = useState(initialForm); const [tab, setTab] = useState<Tab>("general"); const [files, setFiles] = useState<File[]>([]); const [payments, setPayments] = useState<InsurancePaymentEntry[]>([]);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [errors, setErrors] = useState<Errors>({});
  function update(name: keyof typeof initialForm, value: string | boolean | InsuranceCaseType[]) { setForm((current) => ({ ...current, [name]: value })); }
  function updateIdentity(name: "identityNumber" | "opposingIdentityNumber", value: string) { update(name, value.replace(/\D/g, "").slice(0, 11)); }
  function updateDate(name: keyof typeof initialForm, value: string) { setForm((current) => ({ ...current, [name]: limitDateYear(value, String(current[name])) })); }
  function setArbitration(value: boolean) { setForm((current) => ({ ...current, hasArbitration: value, ...(!value ? { arbitrationApplicationDate: "", arbitrationApplicationNo: "", arbitrationCaseNumber: "" } : {}) })); }
  function toggleCaseType(value: InsuranceCaseType) { setForm((current) => ({ ...current, caseTypes: current.caseTypes.includes(value) ? current.caseTypes.filter((item) => item !== value) : [...current.caseTypes, value] })); }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (saving) return; setSaving(true); setError(""); setErrors({});
    try {
      const response = await fetch("/api/insurance-arbitration", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, arbitrationApplicationNo: form.arbitrationApplicationNo || null, opposingPolicyNumber: form.opposingPolicyNumber || null, policyExpiryDate: form.policyExpiryDate || null, opposingVehicleOwner: form.opposingVehicleOwner || null, opposingIdentityNumber: form.opposingIdentityNumber || null, identityNumber: form.identityNumber || null, postalDeliveryDate: form.postalDeliveryDate || null, insuranceApplicationDate: form.insuranceApplicationDate || null, arbitrationApplicationDate: form.arbitrationApplicationDate || null, arbitrationCaseNumber: form.arbitrationCaseNumber || null, description: form.description || null, payments: payments.map((payment) => ({ type: payment.type, paymentDate: payment.paymentDate, amount: payment.amount, commission: payment.commission, description: payment.description || null })) }) });
      const body = await response.json(); if (!response.ok || !body.data) { setErrors(body.error?.fields ?? {}); throw new Error(body.error?.message ?? "Dosya kaydedilemedi."); }
      for (const file of files) { const data = new FormData(); data.append("file", file); const upload = await fetch(`/api/insurance-arbitration/${body.data.id}/documents`, { method: "POST", credentials: "same-origin", body: data }); if (!upload.ok) throw new Error(`${file.name} yüklenemedi; dosya kaydı oluşturuldu.`); }
      router.push(`/sigorta-ve-tahkim?created=${encodeURIComponent(body.data.referenceNumber)}`);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Dosya kaydedilemedi."); setSaving(false); }
  }
  const text = (name: keyof typeof initialForm, label: string, required = false, type = "text", disabled = false) => <label><span>{label}{required && " *"}</span><input type={type} max={type === "date" ? "9999-12-31" : undefined} required={required} disabled={disabled} value={String(form[name])} onChange={(e) => type === "date" ? updateDate(name, e.target.value) : update(name, e.target.value)} />{errors[name]?.[0] && <small>{errors[name]?.[0]}</small>}</label>;
  const identity = (name: "identityNumber" | "opposingIdentityNumber", label: string) => <label><span>{label}</span><input inputMode="numeric" maxLength={11} value={form[name]} onChange={(e) => updateIdentity(name, e.target.value)} placeholder="En fazla 11 rakam" />{errors[name]?.[0] && <small>{errors[name]?.[0]}</small>}</label>;
  const money = (name: MoneyField, label: string) => <label><span>{label}</span><div className={styles.money}><input inputMode="decimal" value={form[name]} onChange={(e) => update(name, formatMoneyInput(e.target.value))} /><b>TL</b></div>{errors[name]?.[0] && <small>{errors[name]?.[0]}</small>}</label>;
  return <AppShell><main className={styles.page}><header className={styles.header}><div><Link href="/sigorta-ve-tahkim">←</Link><h1>Yeni Dosya</h1><p>Sigorta ve tahkim dosya bilgilerini eksiksiz giriniz.</p></div><div><Link href="/sigorta-ve-tahkim">İptal</Link><button form="insurance-case-form" disabled={saving}>{saving ? "Kaydediliyor…" : "Kaydet"}</button></div></header>
    <nav className={styles.tabs}>{([["general","Genel Bilgiler"],["payments","Ödemeler"],["description","Açıklama & Süreç"],["documents",`Belgeler (${files.length})`]] as Array<[Tab,string]>).map(([key,label]) => <button type="button" key={key} className={tab === key ? styles.activeTab : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {error && <p className={styles.error}>{error}</p>}<form id="insurance-case-form" onSubmit={submit}>
      {tab === "general" && <div className={styles.general}>
        <Section number="1" title="Karşı Taraf Bilgileri" tone="blue"><div className={styles.grid5}>{text("opposingInsuranceCompany", "Karşı Sigorta", true)}{text("opposingPolicyNumber", "Karşı Poliçe No")}{text("policyExpiryDate", "Poliçe Vadesi", false, "date")}{text("opposingVehicleOwner", "Karşı Araç Sahibi")}{identity("opposingIdentityNumber", "Karşı TC / VKN")}</div></Section>
        <Section number="2" title="Araç ve Kaza Bilgileri" tone="blue"><div className={styles.grid5}>{text("vehicleOwner", "Araç Sahibi / Müvekkil", true)}{identity("identityNumber", "TC / VKN")}{text("vehiclePlate", "Araç Plaka", true)}{text("accidentDate", "Kaza Tarihi", true, "date")}{text("postalDeliveryDate", "Posta Teslim", false, "date")}</div></Section>
        <Section number="3" title="Dosya Türü" tone="gold"><div className={styles.radios}>{Object.entries(INSURANCE_CASE_TYPE_LABELS).map(([value,label]) => <label key={value}><input type="checkbox" checked={form.caseTypes.includes(value as InsuranceCaseType)} onChange={() => toggleCaseType(value as InsuranceCaseType)} />{label}</label>)}</div>{errors.caseTypes?.[0] && <small>{errors.caseTypes[0]}</small>}</Section>
        <div className={styles.split}><Section number="4" title="Sigorta Bilgileri" tone="green"><div className={styles.grid2}>{text("insuranceApplicationDate", "Sigorta Başvurusu Tarihi", false, "date")}{money("insuranceSettlementOffer", "Sigorta Sulh Teklifi")}</div></Section><Section number="5" title="Tahkim Bilgileri" tone="cyan"><div className={styles.gridTahkim}><label><span>Tahkim Var / Yok</span><select value={form.hasArbitration ? "yes" : "no"} onChange={(e) => setArbitration(e.target.value === "yes")}><option value="no">Yok</option><option value="yes">Var</option></select></label>{text("arbitrationApplicationDate", "Tahkim Başvuru Tarihi", false, "date", !form.hasArbitration)}{text("arbitrationApplicationNo", "Tahkim Başvuru No", false, "text", !form.hasArbitration)}{text("arbitrationCaseNumber", "Tahkim Esas No", false, "text", !form.hasArbitration)}<label><span>Dosyanın Son Durumu</span><select value={form.status} onChange={(e) => update("status", e.target.value)}>{Object.entries(INSURANCE_STATUS_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></Section></div>
        <Section number="6" title="Masraf Bilgileri" tone="purple"><div className={styles.grid6}>{money("postageExpense", "Pul Gideri")}{money("enforcementExpense", "İcra Masrafı")}{money("arbitrationApplicationFee", "Tahkim Başvuru Ücreti")}{money("expertFee", "Bilirkişi Ücreti")}{money("postalAmount", "Posta Rakamı")}{money("actualDepreciationAmount", "Gerçek Değer Kaybı")}</div></Section>
      </div>}
      {tab === "payments" && <PaymentSection payments={payments} onChange={setPayments} />}
      {tab === "description" && <section className={`${styles.tabPanel} ${styles.descriptionPanel}`}><h2>Açıklama & Süreç</h2><p>Dosyanın genel açıklamasını ve süreç notunu yazın.</p><textarea maxLength={500} value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="Açıklama giriniz…" /><b>{form.description.length} / 500</b></section>}
      {tab === "documents" && <section className={`${styles.tabPanel} ${styles.documentPanel}`}><h2>Belgeler</h2><p>PDF, JPG veya PNG belgeleri ekleyin. Her belge en fazla 20 MB olabilir.</p><label className={styles.dropzone}><input type="file" accept=".pdf,.jpg,.jpeg,.png" multiple onChange={(e) => setFiles((current) => [...current, ...Array.from(e.target.files ?? [])])} /><strong>Belge seçin veya buraya sürükleyin</strong></label><div className={styles.fileList}>{files.map((file,index) => <div key={`${file.name}-${index}`}><span>{file.name}</span><small>{Math.ceil(file.size / 1024)} KB</small><button type="button" onClick={() => setFiles((current) => current.filter((_,itemIndex) => itemIndex !== index))}>×</button></div>)}</div></section>}
    </form></main></AppShell>;
}
function Section({ number, title, tone, children }: { number: string; title: string; tone: "blue" | "gold" | "green" | "cyan" | "purple"; children: React.ReactNode }) { return <section className={`${styles.section} ${styles[tone]}`}><h2><span>{number}</span>{title}</h2>{children}</section>; }
