"use client";

import { useMemo, useState } from "react";
import { centsToMoneyString, formatMoneyInput, limitDateYear, parseMoneyToCents } from "@/lib/form-input";
import styles from "./PaymentSection.module.css";

export type InsurancePaymentType = "OUTGOING_PAYMENT" | "INSURANCE_INCOME" | "ARBITRATION_INCOME" | "ENFORCEMENT_INCOME";
export type InsurancePaymentEntry = { clientId: string; type: InsurancePaymentType; paymentDate: string; amount: string; commission: string; description: string };
const labels: Record<InsurancePaymentType, string> = { OUTGOING_PAYMENT: "Yapılan Ödeme", INSURANCE_INCOME: "Sigortadan Gelen", ARBITRATION_INCOME: "Tahkimden Gelen", ENFORCEMENT_INCOME: "İcradan Gelen" };

export default function PaymentSection({ payments, onChange }: { payments: InsurancePaymentEntry[]; onChange: (payments: InsurancePaymentEntry[]) => void }) {
  const [editingId, setEditingId] = useState(""); const [type, setType] = useState<InsurancePaymentType>("OUTGOING_PAYMENT"); const [date, setDate] = useState(""); const [amount, setAmount] = useState(""); const [commission, setCommission] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  const amountCents = parseMoneyToCents(amount) ?? 0n; const commissionCents = parseMoneyToCents(commission) ?? 0n; const clientCents = amountCents > commissionCents ? amountCents - commissionCents : 0n;
  const totals = useMemo(() => payments.reduce((sum, item) => { const value = parseMoneyToCents(item.amount) ?? 0n; const fee = parseMoneyToCents(item.commission) ?? 0n; if (item.type === "OUTGOING_PAYMENT") sum.outgoing += value; else sum.incoming += value; sum.commission += fee; sum.client += value > fee ? value - fee : 0n; return sum; }, { outgoing: 0n, incoming: 0n, commission: 0n, client: 0n }), [payments]);
  function reset() { setEditingId(""); setType("OUTGOING_PAYMENT"); setDate(""); setAmount(""); setCommission(""); setDescription(""); }
  function save() { setMessage(""); if (!date || amountCents <= 0n) { setMessage("Tarih ve sıfırdan büyük tutar giriniz."); return; } if (commissionCents > amountCents) { setMessage("Komisyon tutardan büyük olamaz."); return; } const entry = { clientId: editingId || crypto.randomUUID(), type, paymentDate: date, amount, commission: commission || "0", description: description.trim() }; onChange(editingId ? payments.map((item) => item.clientId === editingId ? entry : item) : [entry, ...payments]); setMessage(editingId ? "Ödeme güncellendi." : "Ödeme listeye eklendi."); reset(); }
  function edit(item: InsurancePaymentEntry) { setEditingId(item.clientId); setType(item.type); setDate(item.paymentDate); setAmount(item.amount); setCommission(item.commission); setDescription(item.description); }
  function remove(id: string) { onChange(payments.filter((item) => item.clientId !== id)); if (editingId === id) reset(); }
  return <section className={styles.panel}><header><h2>▣ Ödeme Girişi</h2><p>Dosyaya ait yapılan veya gelen ödemeleri kaydedebilirsiniz.</p></header>
    <div className={styles.form}><label>Ödeme Türü *<select value={type} onChange={(e) => setType(e.target.value as InsurancePaymentType)}>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Ödeme Tarihi *<input required type="date" max="9999-12-31" value={date} onChange={(e) => setDate(limitDateYear(e.target.value, date))} /></label><Money label="Tutar *" value={amount} onChange={setAmount} /><Money label="Komisyon Tutarı" value={commission} onChange={setCommission} /><label>Müvekkile Ödenecek Tutar<div className={styles.readonly}>{centsToMoneyString(clientCents)} TL</div></label><label className={styles.description}>Açıklama<textarea maxLength={500} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Açıklama giriniz…" /><small>{description.length} / 500</small></label><div className={styles.formActions}>{editingId && <button type="button" onClick={reset}>Vazgeç</button>}<button type="button" onClick={save}>{editingId ? "Değişikliği Kaydet" : "Ödemeyi Ekle"}</button></div>{message && <p className={styles.message}>{message}</p>}</div>
    <div className={styles.summary}><article><span>Toplam Yapılan Ödeme</span><b>{money(totals.outgoing)} TL</b></article><article><span>Toplam Gelen Ödeme</span><b>{money(totals.incoming)} TL</b></article><article><span>Toplam Komisyon</span><b>{money(totals.commission)} TL</b></article><article><span>Toplam Müvekkile Ödenen</span><b>{money(totals.client)} TL</b></article></div>
    <section className={styles.records}><h3>▣ Kayıtlı Ödemeler</h3><div><table><thead><tr><th>#</th><th>Tarih</th><th>Ödeme Türü</th><th>Tutar</th><th>Komisyon</th><th>Müvekkile Tutar</th><th>Açıklama</th><th>İşlemler</th></tr></thead><tbody>{payments.map((item,index) => { const value=parseMoneyToCents(item.amount)??0n; const fee=parseMoneyToCents(item.commission)??0n; return <tr key={item.clientId}><td>{index+1}</td><td>{formatDate(item.paymentDate)}</td><td><span className={item.type === "OUTGOING_PAYMENT" ? styles.outgoing : styles.incoming}>{labels[item.type]}</span></td><td>{item.type === "OUTGOING_PAYMENT" ? "−" : "+"} {money(value)} TL</td><td>{money(fee)} TL</td><td>{money(value>fee?value-fee:0n)} TL</td><td><span className={styles.tooltip} title={item.description || "Açıklama yok"} data-tooltip={item.description || "Açıklama yok"}>{item.description || "—"}</span></td><td><button type="button" title="Düzenle" onClick={() => edit(item)}><ActionIcon name="edit" /></button><button type="button" title="Sil" onClick={() => remove(item.clientId)}><ActionIcon name="delete" /></button></td></tr>})}{payments.length===0&&<tr><td colSpan={8} className={styles.empty}>Henüz ödeme kaydı eklenmedi.</td></tr>}</tbody></table></div></section>
  </section>;
}
function Money({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) { return <label>{label}<div className={styles.money}><input inputMode="decimal" value={value} onChange={(e)=>onChange(formatMoneyInput(e.target.value))} placeholder="0,00" /><b>TL</b></div></label>; }
function money(value: bigint) { return centsToMoneyString(value); }
function formatDate(value:string){const [year,month,day]=value.split("-");return `${day}.${month}.${year}`;}
function ActionIcon({ name }: { name: "edit" | "delete" }) { return <svg viewBox="0 0 24 24" aria-hidden="true">{name === "edit" ? <path d="M4 20h4l11-11-4-4L4 16v4Zm10-13 4 4m-2-6 2-2 4 4-2 2" /> : <path d="M4 7h16M9 7V4h6v3m-8 0 1 14h8l1-14M10 11v6m4-6v6" />}</svg>; }
