"use client";

import { FormEvent, useState } from "react";
import { formatTimeInput, isValidTime, limitDateYear } from "@/lib/form-input";
import styles from "./CaseActivityTabs.module.css";

type Note = { id: string; content: string; createdAt: string; author: { name: string } };
type Reminder = { id: string; title: string; dueAt: string; status: string };
type DocumentCategory = "ALL" | "PAYMENT" | "NOTIFICATION" | "OTHER";
type Document = { id: string; originalName: string; sizeBytes: number; category: string; createdAt: string };

export function NotesTab({ caseId, initialItems }: { caseId: string; initialItems: Note[] }) {
  const [items, setItems] = useState(initialItems); const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!content.trim() || saving) return; setSaving(true); setMessage(""); try { const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/notes`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const body = await response.json(); if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Not eklenemedi."); setItems((current) => [{ id: body.data.id, content: content.trim(), createdAt: body.data.createdAt, author: { name: "Siz" } }, ...current]); setContent(""); setMessage("Not eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Not eklenemedi."); } finally { setSaving(false); } }
  return <ActivityShell title="Notlar" subtitle="Dosyayla ilgili çalışma notlarını ekip içinde saklayın."><form className={styles.composer} onSubmit={submit}><textarea required maxLength={2000} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Dosyayla ilgili notunuzu yazın…" /><footer><span>{content.length} / 2000</span><button disabled={saving}>{saving ? "Ekleniyor…" : "Not Ekle"}</button></footer></form>{message && <p className={styles.message}>{message}</p>}<div className={styles.timeline}>{items.map((item) => <article key={item.id}><div className={styles.avatar}>{initials(item.author.name)}</div><div><header><b>{item.author.name}</b><time>{dateTime(item.createdAt)}</time></header><p>{item.content}</p></div></article>)}{!items.length && <Empty text="Henüz not eklenmedi." />}</div></ActivityShell>;
}

export function NotificationsTab({ caseId, initialItems }: { caseId: string; initialItems: Reminder[] }) {
  const [items, setItems] = useState(initialItems); const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !date || !isValidTime(time) || saving) return; setSaving(true); setMessage(""); try { const dueAt = new Date(`${date}T${time}`).toISOString(); const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/reminders`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, dueAt }) }); const body = await response.json(); if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Bildirim eklenemedi."); setItems((current) => [...current, { id: body.data.id, title: title.trim(), dueAt: body.data.dueAt, status: body.data.status }].sort((a,b) => a.dueAt.localeCompare(b.dueAt))); setTitle(""); setDate(""); setTime(""); setMessage("Bildirim eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Bildirim eklenemedi."); } finally { setSaving(false); } }
  return <ActivityShell title="Bildirimler" subtitle="Takip tarihini belirleyin; zamanı geldiğinde aktif yöneticilere e-posta gönderilsin."><form className={styles.notificationForm} onSubmit={submit}><label><span>Bildirim Başlığı</span><input required maxLength={500} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Örn: Ödeme vadesini kontrol et" /></label><label><span>Tarih</span><input required type="date" max="9999-12-31" value={date} onChange={(event) => setDate(limitDateYear(event.target.value, date))} /></label><label><span>Saat</span><input required inputMode="numeric" maxLength={5} value={time} onChange={(event) => setTime(formatTimeInput(event.target.value, time))} placeholder="SS:DD" /></label><button disabled={saving}>{saving ? "Ekleniyor…" : "Bildirim Ekle"}</button></form>{message && <p className={styles.message}>{message}</p>}<div className={styles.reminders}>{items.map((item) => <article key={item.id}><span className={styles.bell}>♧</span><div><b>{item.title}</b><time>{dateTime(item.dueAt)}</time></div><em>{status(item.status)}</em></article>)}{!items.length && <Empty text="Henüz bildirim eklenmedi." />}</div></ActivityShell>;
}

export function DocumentsTab({ caseId, initialItems }: { caseId: string; initialItems: Document[] }) {
  const [items, setItems] = useState(initialItems); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const [folder, setFolder] = useState<DocumentCategory>("ALL"); const [uploadFolder, setUploadFolder] = useState<Exclude<DocumentCategory,"ALL">>("OTHER");
  async function upload(files: File[]) { if (!files.length || uploading) return; setUploading(true); setMessage(""); let failed = 0; const added: Document[] = []; for (const file of files) { const data = new FormData(); data.set("file", file); data.set("documentName", file.name.replace(/\.[^.]+$/, "")); data.set("category", uploadFolder); const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/documents`, { method: "POST", credentials: "same-origin", body: data }); const body = await response.json(); if (!response.ok || !body.data) failed += 1; else added.push(body.data); } setItems((current) => [...added, ...current]); setMessage(failed ? `${failed} evrak yüklenemedi.` : `${added.length} evrak yüklendi.`); setUploading(false); }
  const visible = folder === "ALL" ? items : items.filter((item) => item.category === folder);
  const folders: Array<[DocumentCategory,string]> = [["ALL","Tüm Evraklar"],["PAYMENT","Ödeme Belgeleri"],["NOTIFICATION","Tebligatlar"],["OTHER","Diğer Evraklar"]];
  return <ActivityShell title="Evraklar" subtitle="Dosyaya bağlı belgeleri klasörleyerek yükleyin ve görüntüleyin."><div className={styles.uploadRow}><label><span>Yüklenecek Klasör</span><select value={uploadFolder} onChange={(event) => setUploadFolder(event.target.value as Exclude<DocumentCategory,"ALL">)}><option value="PAYMENT">Ödeme Belgeleri</option><option value="NOTIFICATION">Tebligatlar</option><option value="OTHER">Diğer Evraklar</option></select></label><label className={styles.dropzone}><input type="file" multiple accept="application/pdf,image/jpeg,image/png" onChange={(event) => void upload(Array.from(event.target.files ?? []))} /><b>{uploading ? "Evraklar yükleniyor…" : "Evrakları buraya bırakın veya seçin"}</b><span>PDF, JPG veya PNG · Belge başına en fazla 20 MB</span></label></div>{message && <p className={styles.message}>{message}</p>}<div className={styles.documentLayout}><aside><strong>Klasörler</strong>{folders.map(([key,label]) => <button className={folder === key ? styles.selectedFolder : ""} onClick={() => setFolder(key)} key={key} type="button">{folder === key ? "▾" : "›"} {label} <span>{key === "ALL" ? items.length : items.filter((item) => item.category === key).length}</span></button>)}</aside><div className={styles.documents}>{visible.map((item) => <a key={item.id} href={`/api/cases/${encodeURIComponent(caseId)}/documents/${encodeURIComponent(item.id)}`}><span>▤</span><div><b>{item.originalName}</b><small>{bytes(item.sizeBytes)} · {dateTime(item.createdAt)}</small></div><em>Görüntüle</em></a>)}{!visible.length && <Empty text="Bu klasörde evrak bulunmuyor." />}</div></div></ActivityShell>;
}

function ActivityShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className={styles.shell}><header><h2>{title}</h2><p>{subtitle}</p></header>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className={styles.empty}>{text}</div>; }
function initials(name: string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]?.toLocaleUpperCase("tr-TR")).join("") || "K"; }
function dateTime(value: string) { return new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Istanbul" }).format(new Date(value)); }
function bytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
function status(value: string) { return ({ PENDING: "Bekliyor", SENT: "Gönderildi", FAILED: "Başarısız", CANCELLED: "İptal" } as Record<string,string>)[value] ?? value; }
