"use client";

import { FormEvent, useRef, useState } from "react";
import { formatTimeInput, isValidTime, limitDateYear } from "@/lib/form-input";
import styles from "./CaseActivityTabs.module.css";

export type DraftNote = { id: string; content: string; createdAt: string; author: { name: string } };
export type DraftReminder = { id: string; title: string; dueAt: string; status: string };
type Note = DraftNote;
type Reminder = DraftReminder;
type DocumentCategory = "ALL" | "PAYMENT" | "NOTIFICATION" | "OTHER";
export type DraftDocument = { id: string; originalName: string; sizeBytes: number; category: string; createdAt: string; file?: File };
type Document = DraftDocument;

export function NotesTab({ caseId, initialItems, onDraftItemsChange }: { caseId?: string; initialItems: Note[]; onDraftItemsChange?: (items: Note[]) => void }) {
  const [items, setItems] = useState(initialItems); const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!content.trim() || saving) return; if(!caseId){const next=[{id:crypto.randomUUID(),content:content.trim(),createdAt:new Date().toISOString(),author:{name:"Siz"}},...items];setItems(next);onDraftItemsChange?.(next);setContent("");setMessage("Taslak not eklendi.");return;} setSaving(true); setMessage(""); try { const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/notes`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const body = await response.json(); if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Not eklenemedi."); setItems((current) => [{ id: body.data.id, content: content.trim(), createdAt: body.data.createdAt, author: { name: "Siz" } }, ...current]); setContent(""); setMessage("Not eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Not eklenemedi."); } finally { setSaving(false); } }
  return <ActivityShell title="Notlar" subtitle="Dosyayla ilgili çalışma notlarını ekip içinde saklayın."><form className={styles.composer} onSubmit={submit}><header><div><h3>Yeni Not Ekle</h3><p>Dosyanın takibi için gerekli ayrıntıları kaydedin.</p></div><span>{content.length} / 2.000</span></header><textarea required maxLength={2000} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Dosyayla ilgili notunuzu yazın…" /><footer><div className={styles.noteMeta}><span>Genel Not</span><span>Tüm Ekip</span></div><button disabled={!content.trim() || saving}>{saving ? "Ekleniyor…" : "+ Notu Ekle"}</button></footer></form>{message && <p className={styles.message}>{message}</p>}<section className={styles.noteList}><header><div><h3>Notlar <span>{items.length}</span></h3><p>En yeni notlar üstte gösterilir.</p></div></header><div className={styles.timeline}>{items.map((item) => <article key={item.id}><div className={styles.avatar}>{initials(item.author.name)}</div><div><header><b>{item.author.name}</b><time>{dateTime(item.createdAt)}</time></header><p>{item.content}</p><small>Tüm ekip</small></div></article>)}{!items.length && <Empty text="Henüz not eklenmedi" detail="Gerektiğinde yukarıdan yeni bir not ekleyebilirsiniz." icon="✎" />}</div></section></ActivityShell>;
}

export function NotificationsTab({ caseId, initialItems, onDraftItemsChange }: { caseId?: string; initialItems: Reminder[]; onDraftItemsChange?: (items: Reminder[]) => void }) {
  const [items, setItems] = useState(initialItems); const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !date || !isValidTime(time) || saving) return; const dueAt = new Date(`${date}T${time}`).toISOString(); if(!caseId){const next=[...items,{id:crypto.randomUUID(),title:title.trim(),dueAt,status:"PENDING"}].sort((a,b)=>a.dueAt.localeCompare(b.dueAt));setItems(next);onDraftItemsChange?.(next);setTitle("");setDate("");setTime("");setMessage("Taslak bildirim eklendi.");return;} setSaving(true); setMessage(""); try { const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/reminders`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, dueAt }) }); const body = await response.json(); if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Bildirim eklenemedi."); setItems((current) => [...current, { id: body.data.id, title: title.trim(), dueAt: body.data.dueAt, status: body.data.status }].sort((a,b) => a.dueAt.localeCompare(b.dueAt))); setTitle(""); setDate(""); setTime(""); setMessage("Bildirim eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Bildirim eklenemedi."); } finally { setSaving(false); } }
  return <ActivityShell title="Bildirimler" subtitle="Takip tarihini belirleyin; zamanı geldiğinde aktif yöneticilere e-posta gönderilsin."><form className={styles.notificationForm} onSubmit={submit}><label><span>Bildirim Başlığı</span><input required maxLength={500} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Örn: Ödeme vadesini kontrol et" /></label><label><span>Tarih</span><input required type="date" max="9999-12-31" value={date} onChange={(event) => setDate(limitDateYear(event.target.value, date))} /></label><label><span>Saat</span><input required inputMode="numeric" maxLength={5} value={time} onChange={(event) => setTime(formatTimeInput(event.target.value, time))} placeholder="SS:DD" /></label><button disabled={saving}>{saving ? "Ekleniyor…" : "Bildirim Ekle"}</button></form>{message && <p className={styles.message}>{message}</p>}<div className={styles.reminders}>{items.map((item) => <article key={item.id}><span className={styles.bell}>♧</span><div><b>{item.title}</b><time>{dateTime(item.dueAt)}</time></div><em>{status(item.status)}</em></article>)}{!items.length && <Empty text="Henüz bildirim eklenmedi." />}</div></ActivityShell>;
}

export function DocumentsTab({ caseId, initialItems, onDraftItemsChange }: { caseId?: string; initialItems: Document[]; onDraftItemsChange?: (items: Document[]) => void }) {
  const input = useRef<HTMLInputElement>(null); const [items, setItems] = useState(initialItems); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const [folder, setFolder] = useState<DocumentCategory>("ALL"); const [search, setSearch] = useState("");
  async function upload(files: File[]) { const accepted = files.filter((file) => file.size > 0 && file.size <= 20 * 1024 * 1024 && ["application/pdf", "image/jpeg", "image/png"].includes(file.type)); if (!accepted.length || uploading) { if (files.length) setMessage("Yalnızca 20 MB veya daha küçük PDF, JPG ve PNG dosyaları eklenebilir."); return; } const targetFolder: Exclude<DocumentCategory,"ALL"> = folder === "ALL" ? "OTHER" : folder; if(!caseId){const added=accepted.map((file)=>({id:crypto.randomUUID(),originalName:file.name,sizeBytes:file.size,category:targetFolder,createdAt:new Date().toISOString(),file}));const next=[...added,...items];setItems(next);onDraftItemsChange?.(next);setMessage(`${added.length} evrak taslağa eklendi.`);return;} setUploading(true); setMessage(""); let failed = files.length - accepted.length; const added: Document[] = []; for (const file of accepted) { const data = new FormData(); data.set("file", file); data.set("documentName", file.name.replace(/\.[^.]+$/, "")); data.set("category", targetFolder); const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/documents`, { method: "POST", credentials: "same-origin", body: data }); const body = await response.json(); if (!response.ok || !body.data) failed += 1; else added.push(body.data); } setItems((current) => [...added, ...current]); setMessage(failed ? `${failed} evrak yüklenemedi.` : `${added.length} evrak yüklendi.`); setUploading(false); }
  const visible = (folder === "ALL" ? items : items.filter((item) => item.category === folder)).filter((item) => item.originalName.toLocaleLowerCase("tr-TR").includes(search.trim().toLocaleLowerCase("tr-TR")));
  const folders: Array<[DocumentCategory,string]> = [["ALL","Tüm Evraklar"],["PAYMENT","Ödeme Belgeleri"],["NOTIFICATION","Tebligatlar"],["OTHER","Diğer Evraklar"]];
  return <ActivityShell title="Evraklar" subtitle="Dosyaları klasörlere ayırın ve kolayca görüntüleyin." action={<button type="button" className={styles.uploadButton} onClick={() => input.current?.click()}>+ Evrak Yükle</button>}><input ref={input} className={styles.fileInput} type="file" multiple accept="application/pdf,image/jpeg,image/png" onChange={(event) => void upload(Array.from(event.target.files ?? []))} />{message && <p className={styles.message}>{message}</p>}<div className={styles.documentLayout}><aside><strong>Klasörler</strong>{folders.map(([key,label]) => <button className={folder === key ? styles.selectedFolder : ""} onClick={() => setFolder(key)} key={key} type="button"><span>{folder === key ? "▾" : "›"}　▰ {label}</span><b>{key === "ALL" ? items.length : items.filter((item) => item.category === key).length}</b></button>)}</aside><section className={styles.documentArea}><div className={styles.documentFilters}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Evrak adına göre ara" /><span>{visible.length} evrak gösteriliyor</span></div><button type="button" className={styles.dropzone} onClick={() => input.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void upload(Array.from(event.dataTransfer.files)); }}><b>{uploading ? "Evraklar yükleniyor…" : "Dosyaları buraya bırakın veya seçin"}</b><span>PDF, JPG veya PNG · Her dosya en fazla 20 MB</span></button><div className={styles.documents}>{visible.map((item) => caseId ? <a key={item.id} href={`/api/cases/${encodeURIComponent(caseId)}/documents/${encodeURIComponent(item.id)}`}><span>▤</span><div><b>{item.originalName}</b><small>{bytes(item.sizeBytes)} · {dateTime(item.createdAt)}</small></div><em>Görüntüle</em></a> : <div className={styles.draftDocument} key={item.id}><span>▤</span><div><b>{item.originalName}</b><small>{bytes(item.sizeBytes)} · Kaydetmeye hazır</small></div></div>)}{!visible.length && <Empty text="Bu klasörde evrak yok" detail="Evrak yükleyebilir veya farklı bir klasör seçebilirsiniz." icon="▤" />}</div></section></div></ActivityShell>;
}

function ActivityShell({ title, subtitle, action, children }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className={styles.shell}><header><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</header>{children}</section>; }
function Empty({ text, detail, icon }: { text: string; detail?: string; icon?: string }) { return <div className={styles.empty}>{icon && <i>{icon}</i>}<b>{text}</b>{detail && <span>{detail}</span>}</div>; }
function initials(name: string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]?.toLocaleUpperCase("tr-TR")).join("") || "K"; }
function dateTime(value: string) { return new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Istanbul" }).format(new Date(value)); }
function bytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
function status(value: string) { return ({ PENDING: "Bekliyor", SENT: "Gönderildi", FAILED: "Başarısız", CANCELLED: "İptal" } as Record<string,string>)[value] ?? value; }
