ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'EXPENSE_REFUND';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'PENALTY_COMPENSATION';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'OTHER_INCOME';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'FEE';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'NOTIFICATION';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'EXPERT_FEE';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'ATTORNEY_PAYMENT';
ALTER TYPE "CaseTransactionCategory" ADD VALUE IF NOT EXISTS 'OTHER_EXPENSE';
